version: '3.4'

services:
  lacosterafrontend:
    image: lacosterafrontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 7081:7081
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
