version: '3.4'

services:
  lacosterafrontend:
    image: lacosterafrontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 7081:7081
